### ISSUE TITLE
php artisan serve error

### ISSUE THREAD

**Issue by qwerty0606** [OthmaneBlial/School-Management-System-using-Laravel5.4#2]
[2017-05-24 14:02:07] production.ERROR: RuntimeException: The only supported ciphers are AES-128-CBC and AES-256-CBC with the correct key lengths. in /Users/andrei/Downloads/School-Management-System-using-Laravel5.4-master/Shcool management/vendor/laravel/framework/src/Illuminate/Encryption/Encrypter.php:43
Stack trace:
#0 /Users/andrei/Downloads/School-Management-System-using-Laravel5.4-master/Shcool management/vendor/laravel/framework/src/Illuminate/Encryption/EncryptionServiceProvider.php(27): Illuminate\Encryption\Encrypter->__construct('', 'AES-256-CBC')
#1 /Users/andrei/Downloads/School-Management-System-using-Laravel5.4-master/Shcool management/vendor/laravel/framework/src/Illuminate/Container/Container.php(678): Illuminate\Encryption\EncryptionServiceProvider->Illuminate\Encryption\{closure}(Object(Illuminate\Foundation\Application))
#2 /Users/andrei/Downloads/School-Management-System-using-Laravel5.4-master/Shcool management/vendor/laravel/framework/src/Illuminate/Container/Container.php(565): Illuminate\Container\Container->build(Object(Closure))
#3 /Users/andrei/Downloads/School-Management-System-using-Laravel5.4-master/Shcool management/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(702): Illuminate\Container\Container->make('encrypter')
#4 /Users/andrei/Downloads/School-Management-System-using-Laravel5.4-master/Shcool management/vendor/laravel/framework/src/Illuminate/Container/Container.php(771): Illuminate\Foundation\Application->make('encrypter')
#5 /Users/andrei/Downloads/School-Management-System-using-Laravel5.4-master/Shcool management/vendor/laravel/framework/src/Illuminate/Container/Container.php(733): Illuminate\Container\Container->resolveClass(Object(ReflectionParameter))
#6 /Users/andrei/Downloads/School-Management-System-using-Laravel5.4-master/Shcool management/vendor/laravel/framework/src/Illuminate/Container/Container.php(708): Illuminate\Container\Container->resolveDependencies(Array)
#7 /Users/andrei/Downloads/School-Management-System-using-Laravel5.4-master/Shcool management/vendor/laravel/framework/src/Illuminate/Container/Container.php(565): Illuminate\Container\Container->build('App\\Http\\Middle...')
#8 /Users/andrei/Downloads/School-Management-System-using-Laravel5.4-master/Shcool management/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(702): Illuminate\Container\Container->make('App\\Http\\Middle...')
#9 /Users/andrei/Downloads/School-Management-System-using-Laravel5.4-master/Shcool management/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(138): Illuminate\Foundation\Application->make('App\\Http\\Middle...')
#10 /Users/andrei/Downloads/School-Management-System-using-Laravel5.4-master/Shcool management/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#11 /Users/andrei/Downloads/School-Management-System-using-Laravel5.4-master/Shcool management/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#12 /Users/andrei/Downloads/School-Management-System-using-Laravel5.4-master/Shcool management/vendor/laravel/framework/src/Illuminate/Routing/Router.php(561): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#13 /Users/andrei/Downloads/School-Management-System-using-Laravel5.4-master/Shcool management/vendor/laravel/framework/src/Illuminate/Routing/Router.php(520): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
#14 /Users/andrei/Downloads/School-Management-System-using-Laravel5.4-master/Shcool management/vendor/laravel/framework/src/Illuminate/Routing/Router.php(498): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#15 /Users/andrei/Downloads/School-Management-System-using-Laravel5.4-master/Shcool management/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(174): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#16 /Users/andrei/Downloads/School-Management-System-using-Laravel5.4-master/Shcool management/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
#17 /Users/andrei/Downloads/School-Management-System-using-Laravel5.4-master/Shcool management/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(30): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#18 /Users/andrei/Downloads/School-Management-System-using-Laravel5.4-master/Shcool management/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): Illuminate\Foundation\Http\Middleware\TransformsRequest->handle(Object(Illuminate\Http\Request), Object(Closure))
#19 /Users/andrei/Downloads/School-Management-System-using-Laravel5.4-master/Shcool management/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#20 /Users/andrei/Downloads/School-Management-System-using-Laravel5.4-master/Shcool management/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(30): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#21 /Users/andrei/Downloads/School-Management-System-using-Laravel5.4-master/Shcool management/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): Illuminate\Foundation\Http\Middleware\TransformsRequest->handle(Object(Illuminate\Http\Request), Object(Closure))
#22 /Users/andrei/Downloads/School-Management-System-using-Laravel5.4-master/Shcool management/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#23 /Users/andrei/Downloads/School-Management-System-using-Laravel5.4-master/Shcool management/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#24 /Users/andrei/Downloads/School-Management-System-using-Laravel5.4-master/Shcool management/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): Illuminate\Foundation\Http\Middleware\ValidatePostSize->handle(Object(Illuminate\Http\Request), Object(Closure))
#25 /Users/andrei/Downloads/School-Management-System-using-Laravel5.4-master/Shcool management/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#26 /Users/andrei/Downloads/School-Management-System-using-Laravel5.4-master/Shcool management/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(46): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#27 /Users/andrei/Downloads/School-Management-System-using-Laravel5.4-master/Shcool management/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#28 /Users/andrei/Downloads/School-Management-System-using-Laravel5.4-master/Shcool management/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#29 /Users/andrei/Downloads/School-Management-System-using-Laravel5.4-master/Shcool management/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#30 /Users/andrei/Downloads/School-Management-System-using-Laravel5.4-master/Shcool management/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(149): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#31 /Users/andrei/Downloads/School-Management-System-using-Laravel5.4-master/Shcool management/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(116): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#32 /Users/andrei/Downloads/School-Management-System-using-Laravel5.4-master/Shcool management/public/index.php(53): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#33 /Users/andrei/Downloads/School-Management-System-using-Laravel5.4-master/Shcool management/server.php(21): require_once('/Users/andrei/D...')
#34 {main}  
[2017-05-24 14:02:07] production.ERROR: RuntimeException: The only supported ciphers are AES-128-CBC and AES-256-CBC with the correct key lengths. in /Users/andrei/Downloads/School-Management-System-using-Laravel5.4-master/Shcool management/vendor/laravel/framework/src/Illuminate/Encryption/Encrypter.php:43
Stack trace:
#0 /Users/andrei/Downloads/School-Management-System-using-Laravel5.4-master/Shcool management/vendor/laravel/framework/src/Illuminate/Encryption/EncryptionServiceProvider.php(27): Illuminate\Encryption\Encrypter->__construct('', 'AES-256-CBC')
#1 /Users/andrei/Downloads/School-Management-System-using-Laravel5.4-master/Shcool management/vendor/laravel/framework/src/Illuminate/Container/Container.php(678): Illuminate\Encryption\EncryptionServiceProvider->Illuminate\Encryption\{closure}(Object(Illuminate\Foundation\Application))
#2 /Users/andrei/Downloads/School-Management-System-using-Laravel5.4-master/Shcool management/vendor/laravel/framework/src/Illuminate/Container/Container.php(565): Illuminate\Container\Container->build(Object(Closure))
#3 /Users/andrei/Downloads/School-Management-System-using-Laravel5.4-master/Shcool management/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(702): Illuminate\Container\Container->make('encrypter')
#4 /Users/andrei/Downloads/School-Management-System-using-Laravel5.4-master/Shcool management/vendor/laravel/framework/src/Illuminate/Container/Container.php(771): Illuminate\Foundation\Application->make('encrypter')
#5 /Users/andrei/Downloads/School-Management-System-using-Laravel5.4-master/Shcool management/vendor/laravel/framework/src/Illuminate/Container/Container.php(733): Illuminate\Container\Container->resolveClass(Object(ReflectionParameter))
#6 /Users/andrei/Downloads/School-Management-System-using-Laravel5.4-master/Shcool management/vendor/laravel/framework/src/Illuminate/Container/Container.php(708): Illuminate\Container\Container->resolveDependencies(Array)
#7 /Users/andrei/Downloads/School-Management-System-using-Laravel5.4-master/Shcool management/vendor/laravel/framework/src/Illuminate/Container/Container.php(565): Illuminate\Container\Container->build('App\\Http\\Middle...')
#8 /Users/andrei/Downloads/School-Management-System-using-Laravel5.4-master/Shcool management/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(702): Illuminate\Container\Container->make('App\\Http\\Middle...')
#9 /Users/andrei/Downloads/School-Management-System-using-Laravel5.4-master/Shcool management/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(213): Illuminate\Foundation\Application->make('App\\Http\\Middle...')
#10 /Users/andrei/Downloads/School-Management-System-using-Laravel5.4-master/Shcool management/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(187): Illuminate\Foundation\Http\Kernel->terminateMiddleware(Object(Illuminate\Http\Request), Object(Illuminate\Http\Response))
#11 /Users/andrei/Downloads/School-Management-System-using-Laravel5.4-master/Shcool management/public/index.php(58): Illuminate\Foundation\Http\Kernel->terminate(Object(Illuminate\Http\Request), Object(Illuminate\Http\Response))
#12 /Users/andrei/Downloads/School-Management-System-using-Laravel5.4-master/Shcool management/server.php(21): require_once('/Users/andrei/D...')
#13 {main}  

how to fix that?

**Comment by mwakaambrose** [comment]
Try Running 
` $ composer instal l`
 ` $ npm install `
 ` $ php artisan key:generate `
